[package]
name = "hex-conservative"
version = "0.0.1"
edition = "2018"
description = "A hex encoding and decoding crate with a conservative MSRV and dependency policy."
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
